### PR TITLE
Update pt_BR.po

### PR DESCRIPTION
**Pull request by marcelocripe**
In 09-18-2021

### CODE REVIEW

**Comment by gijsbers** [comment]
10 out of 127 hunks FAILED to merge.

Better and easier for us if you use the https://github.com/bbidulock/icewm repository.

Thank you for your translations!

**Comment by marcelocripe** [comment]
Hello gijsbers.

I have difficulties using GitHub, everything here is very complicated and not intuitive. Can you copy my file or changes/fixes to your file?
With Poedit I was able to identify 3 sentences with errors and made the corrections, I was able to create the .mo file and test it in antiX Linux from "icewm_pt_BR_GitHub_ice-wm-icewm_marcelocripe_18-09-2021.po".
Thank you for creating and maintaining IceWM.

- - - - -

Olá gijsbers.

Eu tenho dificuldades para utilizar o GitHub, tudo aqui muito complicado e não é intuitivo. Você consegue copiar o meu arquivo ou as alterações/correções para o seu arquivo?
Com o Poedit eu consegui identificar 3 frases com erros e fiz as correções, eu consegui criar o arquivo .mo e testar no antiX Linux a partir do "icewm_pt_BR_GitHub_ice-wm-icewm_marcelocripe_18-09-2021.po".
Obrigado por criar e manter o IceWM.

[icewm_pt_BR_GitHub_ice-wm-icewm_marcelocripe_18-09-2021.zip](https://github.com/ice-wm/icewm/files/7190148/icewm_pt_BR_GitHub_ice-wm-icewm_marcelocripe_18-09-2021.zip)

**Comment by hugok79** [comment]
Use https://l10n.opensuse.org/projects/icewm/icewm-1-4-branch/ for translations.

**Comment by hugok79** [comment]
And follow @gijsbers comment, use https://github.com/bbidulock/icewm

**Comment by marcelocripe** [comment]
Hello gijsbers and hugok79.
I appreciate your explanations.
I was able to upload the file to OpenSuse and make the fixes that the platform notified.
Please use the corrected and revised version on 19-09-2021.
Thank you very much.

- - - - -

Olá gijsbers e hugok79.
Eu agradeço por suas explicações.
Eu consegui enviar o arquivo para o OpenSuse e fazer a correções que a plataforma notificou.
Por favor, utilizem a versão corrigida e revisada no dia 19-09-2021.
Muito obrigado.

**Pull request closed without merging**
